(deftheme nims-theme
  "Created 2013-04-01.")

(custom-theme-set-variables
 'nims-theme
 '(ac-auto-show-menu 0.3)
 '(ac-auto-start t)
 '(ac-delay 0.01)
 '(ac-modes (quote (emacs-lisp-mode lisp-interaction-mode c-mode cc-mode c++-mode java-mode malabar-mode clojure-mode scala-mode scheme-mode ocaml-mode tuareg-mode haskell-mode perl-mode cperl-mode python-mode ruby-mode ecmascript-mode javascript-mode js-mode js2-mode php-mode css-mode makefile-mode sh-mode fortran-mode f90-mode ada-mode xml-mode sgml-mode puppet-mode haml-mode sass-mode)))
 '(ac-quick-help-delay 1.0)
 '(ac-trigger-key nil)
 '(cua-check-pending-input nil)
 '(cua-delete-copy-to-register-0 nil)
 '(cua-delete-selection nil)
 '(cua-enable-cua-keys nil)
 '(cua-enable-register-prefix nil)
 '(cua-rectangle-mark-key [C-w])
 '(cua-remap-control-v nil)
 '(cua-remap-control-z nil)
 '(default-frame-alist (quote ((fringe) (right-fringe) (left-fringe . 1) (internal-border-width . 0) (cursor-type . box) (background-color . "gray7") (background-mode . dark) (background-toolbar-color . "#cccccccccccc") (border-color . "black") (bottom-toolbar-shadow-color . "#7a7a7a7a7a7a") (cursor-color . "yellow") (foreground-color . "White") (mouse-color . "sienna1") (top-toolbar-shadow-color . "#f5f5f5f5f5f5") (tool-bar-lines . 0) (menu-bar-lines . 1))))
 '(egg-git-command "/usr/local/bin/git")
 '(ido-auto-merge-delay-time 0)
 '(ido-auto-merge-work-directories-length -1)
 '(ns-tool-bar-display-mode nil)
 '(ns-tool-bar-size-mode nil)
 '(package-archives (quote (("gnu" . "http://elpa.gnu.org/packages/") ("marmalade" . "http://marmalade-repo.org/packages/") ("tromey" . "http://tromey.com/elpa/"))))
 '(rinari-tags-file-name "tags")
 '(safe-local-variable-values (quote ((eval progn (append ffip-patterns (list "*.haml" "*.scss" "*.yml") "*.coffee")) (ffip-patterns "*.haml" "*.scss" "*.yml" "*.log") (whitespace-line-column . 80) (lexical-binding . t) (ruby-compilation-executable . "ruby") (ruby-compilation-executable . "ruby1.8") (ruby-compilation-executable . "ruby1.9") (ruby-compilation-executable . "rbx") (ruby-compilation-executable . "jruby"))))
 '(show-paren-mode t)
 '(line-number-mode 1)
 '(display-time-mode t)
 '(cua-mode nil)
 '(column-number-mode t)
 '(blink-cursor-mode nil))

(provide-theme 'nims-theme)
